name: CI

on:
  push:
    branches:
      - main

jobs:
  run-pnpm-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2.4.0
        with:
          version: 8.10.5
      - uses: actions/setup-node@v4
        with:
          node-version: 20.8.1
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm types
      - run: pnpm lint
